export enum BookGenre {
  Fiction = 'Fiction',
  NonFiction = 'Non-Fiction',
  Mystery = 'Mystery',
  Fantasy = 'Fantasy',
  ScienceFiction = 'Science Fiction',
  Biography = 'Biography',
  Romance = 'Romance',
  Thriller = 'Thriller',
  Historical = 'Historical',
  Horror = 'Horror',
  Poetry = 'Poetry',
  SelfHelp = 'Self Help',
  Health = 'Health',
  Travel = 'Travel',
  Cookbooks = 'Cookbooks',
  Children = 'Children',
  YoungAdult = 'Young Adult',
  GraphicNovels = 'Graphic Novels',
  Classic = 'Classic',
  Dystopian = 'Dystopian'
}
