export enum BookGenre {
  Fiction = 0,
  NonFiction = 1,
  Mystery = 2,
  Fantasy = 3,
  ScienceFiction = 4,
  Biography = 5,
  Romance = 6,
  Thriller = 7,
  Historical = 8,
  Horror = 9,
  Poetry = 10,
  SelfHelp = 11,
  Health = 12,
  Travel = 13,
  Cookbooks = 14,
  Children = 15,
  YoungAdult = 16,
  GraphicNovels = 17,
  Classic = 18,
  Dystopian = 19
}
