export enum Country {
  Russia = 'Russia',
  Canada = 'Canada',
  China = 'China',
  UnitedStates = 'United States',
  Brazil = 'Brazil',
  Australia = 'Australia',
  India = 'India',
  Argentina = 'Argentina',
  Kazakhstan = 'Kazakhstan',
  Algeria = 'Algeria',
  Greenland = 'Greenland',
  CongoDemocraticRepublic = 'Congo Democratic Republic',
  SaudiArabia = 'Saudi Arabia',
  Mexico = 'Mexico',
  Indonesia = 'Indonesia',
  Sudan = 'Sudan',
  Libya = 'Libya',
  Iran = 'Iran',
  Mongolia = 'Mongolia',
  Peru = 'Peru',
  Belarus = 'Belarus'
}
