@LibraryWebApp.ApiGateway_HostAddress = https://localhost:7000
@LibraryWebApp.AuthService_HostAddress = https://localhost:7001

POST {{LibraryWebApp.ApiGateway_HostAddress}}/auth-service/Auth/login
Content-Type: application/json
Accept: application/json

{
    "login": "kira@gmail.com",  
    "password": "1111"     
}

###

POST {{LibraryWebApp.ApiGateway_HostAddress}}/auth-service/Token/refresh
Content-Type: application/json
Accept: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia2lyYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3MjkxMTMxMzgsImlzcyI6Im15c2VjcmV0aXNzdWVyIiwiYXVkIjoibXlzZWNyZXRhdWRpZW5jZSJ9.SqLqnid3Cioasae4FAjj3GlrJUJOw2FJ4Hyp_VrJA6o",
  "refreshToken": "6eXB05feuX2rFI7qYaklYkzS+ql9qsE6fGLXmzo/yS4="
}

###

POST {{LibraryWebApp.ApiGateway_HostAddress}}/auth-service/Token/refresh
Content-Type: application/json
Accept: application/json

{
{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia2lyYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3MjkxMTMxMTcsImlzcyI6Im15c2VjcmV0aXNzdWVyIiwiYXVkIjoibXlzZWNyZXRhdWRpZW5jZSJ9.tzh1a9ZQlJFM6M2SLzA-nlCbDwiGtx-P0VXVbxNXRRI",
  "refreshToken": "AYA7C6jxUjJvlbW4l1PHeu61BbBRX4E8a+YiIDxVTjI="
}
###

POST {{LibraryWebApp.ApiGateway_HostAddress}}/auth-service/Token/revoke
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia2lyYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3MjkxMTMxMzgsImlzcyI6Im15c2VjcmV0aXNzdWVyIiwiYXVkIjoibXlzZWNyZXRhdWRpZW5jZSJ9.SqLqnid3Cioasae4FAjj3GlrJUJOw2FJ4Hyp_VrJA6o

"/pEI91T7AFOXzy6p2+/7QLTXIEO96SEmpH7z+nL5a4I="